SET NAMES UTF8;
DROP DATABASE IF EXISTS
restaurant;
CREATE DATABASE restaurant CHARSET=UTF8;
USE restaurant;

CREATE TABLE res_admin(
    aid INT PRIMARY KEY AUTO_INCREMENT,
    aname VARCHAR(32) UNIQUE,
    apwd  VARCHAR(64)
);
INSERT INTO res_admin VALUE
(NULL,'admin','123456'),
(NULL,'hhg','988999')